### ISSUE TITLE
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) on PolisMath

### ISSUE THREAD

**Issue by uzzal2k5** [uzzal2k5/polis_container#1]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
18-04-25 10:12:39 fde8e03be878 INFO [polismath.poller:23] - Polling :moderation > 1523786901619
18-04-25 10:12:39 fde8e03be878 INFO [polismath.components.postgres:116] - modpoll 1523786901619
18-04-25 10:12:39 fde8e03be878 ERROR [polismath.components.postgres:124] - moderation polling failed  The server does not support SSL.
18-04-25 10:12:39 fde8e03be878 INFO [polismath.poller:23] - Polling :votes > 1523786901644
18-04-25 10:12:39 fde8e03be878 INFO [polismath.components.postgres:100] - poll 1523786901644
18-04-25 10:12:39 fde8e03be878 ERROR [polismath.components.postgres:107] - polling failed  The server does not support SSL.
org.postgresql.util.PSQLException: The server does not support SSL.
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:307)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:105)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:272)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:193)
	at polismath.components.postgres$poll.invokeStatic(postgres.clj:102)
	at polismath.components.postgres$poll.invoke(postgres.clj:97)
	at polismath.poller$poll$fn__46603$state_machine__17687__auto____46632$fn__46637.invoke(poller.clj:21)
	at polismath.poller$poll$fn__46603$state_machine__17687__auto____46632.invoke(poller.clj:21)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__17705.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__12637.invoke(channels.clj:265)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
18-04-25 10:12:40 fde8e03be878 INFO [polismath.poller:23] - Polling :moderation > 1523786901619
18-04-25 10:12:40 fde8e03be878 INFO [polismath.components.postgres:116] - modpoll 1523786901619
18-04-25 10:12:40 fde8e03be878 ERROR [polismath.components.postgres:124] - moderation polling failed  The server does not support SSL.
18-04-25 10:12:40 fde8e03be878 INFO [polismath.poller:23] - Polling :votes > 1523786901644
18-04-25 10:12:40 fde8e03be878 INFO [polismath.components.postgres:100] - poll 1523786901644
18-04-25 10:12:40 fde8e03be878 ERROR [polismath.components.postgres:107] - polling failed  The server does not support SSL.
org.postgresql.util.PSQLException: The server does not support SSL.
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:307)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:105)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:272)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:193)
	at polismath.components.postgres$poll.invokeStatic(postgres.clj:102)
	at polismath.components.postgres$poll.invoke(postgres.clj:97)
	at polismath.poller$poll$fn__46603$state_machine__17687__auto____46632$fn__46637.invoke(poller.clj:21)
	at polismath.poller$poll$fn__46603$state_machine__17687__auto____46632.invoke(poller.clj:21)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__17705.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__12637.invoke(channels.clj:265)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
18-04-25 10:12:41 fde8e03be878 INFO [polismath.poller:23] - Polling :moderation > 1523786901619
18-04-25 10:12:41 fde8e03be878 INFO [polismath.components.postgres:116] - modpoll 1523786901619
18-04-25 10:12:41 fde8e03be878 ERROR [polismath.components.postgres:124] - moderation polling failed  The server does not support SSL.
18-04-25 10:12:41 fde8e03be878 INFO [polismath.poller:23] - Polling :votes > 1523786901644
18-04-25 10:12:41 fde8e03be878 INFO [polismath.components.postgres:100] - poll 1523786901644
18-04-25 10:12:41 fde8e03be878 ERROR [polismath.components.postgres:107] - polling failed  The server does not support SSL.
org.postgresql.util.PSQLException: The server does not support SSL.
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:307)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:105)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:397)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:272)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:193)
	at polismath.components.postgres$poll.invokeStatic(postgres.clj:102)
	at polismath.components.postgres$poll.invoke(postgres.clj:97)

**Comment by szymonkochanski** [comment]
Hi,
I have the same problem with 
_ERROR [polismath.components.postgres:124] - moderation polling failed The server does not support SSL._
I was wondering if you figured out how to fix it.

**Comment by szymonkochanski** [comment]
Based on https://github.com/pol-is/polisServer/issues/44
The issue goes away by setting 
DATABASE_URL: postgres://polis:polis@polisdb:5432/polis?sslmode=disable
for Polis Math container in docker-compose.yml
